#+TITLE: model-zapper
#+AUTHOR: phdenzel

*** Install

    To properly install ~modelzapper.py~, first run ~configure~ in the root
    directory of the repo.
    #+BEGIN_SRC shell
      ./configure
    #+END_SRC
    This will set up a virtual python environment and download all required
    libraries.
    After the environment and required libraries are downloaded, use ~install~
    #+BEGIN_SRC shell
      ./install
    #+END_SRC
    This will compile the ~glass~ source code into ~src~, and move the build
    into ~libs~ and ~includes~ directories.
    If ~glass~ was compiled without errors, ~modelzapper.py~ should be able to
    run as
    #+BEGIN_SRC shell
      python modelzapper.py [gls.state]
    #+END_SRC

*** Build the app

    Once you configured and installed ~modelzapepr.py~, building the app is
    easy! Enter the virtual environment and run ~py2app~
    #+BEGIN_SRC shell
      source venv/bin/activate
      python setup.py py2app
    #+END_SRC

*** Requirements
    
    The app relies on several python modules which are installable via ~pip~.
    Since the app interfaces with ~glass~, a runnable version of ~glass~ is
    essential.

    - [[https://github.com/phdenzel/glass][glass]]
    - virtualenv
    - numpy
    - scipy
    - Tkinter
    - PIL
    - matplotlib

*** More

    Since it is not really easy to install ~glass~, let alone automatically,
    chances are that the app might have problemn.
    If so, try building it yourself. In order to be able to build the app though,
    ~python~ must be installed as a framework.
    For more details see [[https://github.com/phdenzel/local-python-install][https://github.com/phdenzel/local-python-install]].
