#!/bin/bash
ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
FLAGS="--no-strip --matplotlib-backends 'tkagg'"
echo "Currently in $ROOT";
set -x;

# clean the build
for f in $ROOT/{build,dist}; do
    [ -d "$f" ] && rm -rf "$f"
done;

source $ROOT/activate

python setup.py py2app ${FLAGS} $1

set +x;
